name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions:checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
    
